[package]
name = "tex-rs-dummy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tex-rs = {path = "../tex-rs", features = ["async"]}
tokio = {version = "1.16", features = ["full"]}